### ISSUE TITLE
import is not working in App.css

### ISSUE THREAD

**Issue by MAakula** [primefaces/primereact-typescript-quickstart#1]
@import should be used instead of import. File path in the import is not working too. Here is the updated import version.

@import '../node_modules/primereact/resources/primereact.min.css';
@import '../node_modules/primereact/resources/themes/omega/theme.css';
@import '../node_modules/font-awesome/css/font-awesome.css';

**Comment by srbala** [comment]
This issue resolved, safe to close

**Comment by ralexand56** [comment]
Where do you place that @import
