### ISSUE TITLE
clean solution not working

### ISSUE THREAD

**Issue by ModestasK-zz** [primefaces/primereact-typescript-quickstart#2]
1. git clone
2. npm install
3. npm start

Result:
![image](https://user-images.githubusercontent.com/24589080/35502802-d2a75740-04e6-11e8-92a4-84998a9ada50.png)

commenting out these 3 lines in App.css fixes the issue, but probably breaks the purpose...
```
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/omega/theme.css';
import 'font-awesome/css/font-awesome.css';
```

**Comment by srbala** [comment]
This issue resolved, safe to close
